nginx:
  image: nginx
  restart: always
  ports:
    - 80:80
    - 443:443
  links:
    - wordpress
  volumes_from:
    - wordpress:ro
  volumes:
    - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
    - ./var/log/nginx:/var/log/nginx

wordpress:
  build: wordpress
  # Alpine Version
  # dockerfile: Dockerfile.alpine

  restart: always
  
  links:
    - mysql
    - memcached
  environment:
    WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
    WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

mysql:
  image: mariadb
  restart: always
  volumes:
    - ./var/mysql:/var/lib/mysql
  environment:
    MYSQL_DATABASE: wordpress
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

memcached:
  image: memcached
  restart: always

influxsrv:
  # image: tutum/influxdb:0.8.8
  image: tutum/influxdb:latest
  restart: always
  #container_name: influxsrv
  ports:
    - "8083:8083"
    - "8086:8086"
  expose:
    - "8090"
    - "8099"
  environment:
    - PRE_CREATE_DB=cadvisor

cadvisor:
  image: google/cadvisor
  restart: always
  command:
    - -storage_driver=influxdb
    - -storage_driver_db=cadvisor
    - -storage_driver_host=influxsrv:8086
  ports:
    - "8080:8080"
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  links:
    - influxsrv:influxsrv

grafana:
  image: grafana/grafana
  restart: always
  ports:
    - "3000:3000"
  links:
    - influxsrv:influxsrv
  environment:
    - INFLUXDB_HOST=localhost
    - INFLUXDB_PORT=8086
    - INFLUXDB_NAME=cadvisor
    - INFLUXDB_USER=${INFLUXDB_USER}
    - INFLUXDB_PASS=${INFLUXDB_PASS}
